'use client';

import { motion } from 'framer-motion';
import { Download, Copy, Check, Clock, Users, DollarSign, AlertTriangle, CheckCircle2, Shield } from 'lucide-react';
import { useState } from 'react';
import type { PostMortemReport } from '@/types';

interface PostMortemReportDisplayProps {
  report: PostMortemReport;
}

export default function PostMortemReportDisplay({ report }: PostMortemReportDisplayProps) {
  const [copied, setCopied] = useState(false);

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'P0': return 'bg-error text-white';
      case 'P1': return 'bg-warning text-white';
      case 'P2': return 'bg-yellow-500 text-white';
      case 'P3': return 'bg-blue-500 text-white';
      default: return 'bg-text-secondary text-white';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'resolved': return 'bg-success/10 text-success border-success/20';
      case 'investigating': return 'bg-warning/10 text-warning border-warning/20';
      case 'monitoring': return 'bg-blue-500/10 text-blue-500 border-blue-500/20';
      default: return 'bg-text-secondary/10 text-text-secondary border-text-secondary/20';
    }
  };

  const generateMarkdownReport = () => {
    const duration = report.impact.duration;
    const hours = Math.floor(duration / 60);
    const minutes = duration % 60;
    const durationStr = hours > 0 ? `${hours}h ${minutes}m` : `${minutes} minutes`;

    return `# INCIDENT REPORT — ${report.detectedAt.toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short'
    })}

**Incident ID:** ${report.incidentId}
**Status:** ${report.status.toUpperCase()}

## Summary

**SEVERITY:** ${report.severity} — ${report.title}
**DURATION:** ${durationStr}
**USERS AFFECTED:** ~${report.impact.usersAffected.toLocaleString()}
${report.impact.revenueImpact ? `**REVENUE IMPACT:** ~$${report.impact.revenueImpact.toLocaleString()} (estimated)` : ''}

## Timeline

${report.timeline.map(event =>
      `- **${event.timestamp.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}** — ${event.event}${event.actor ? ` (${event.actor})` : ''}`
    ).join('\n')}

## Root Cause

${report.rootCause}

## Fix Applied

${report.fixApplied}

## Prevention Measures

### Immediate Actions
${report.prevention.immediate.map(item => `- ${item}`).join('\n')}

### Short-term Improvements
${report.prevention.shortTerm.map(item => `- ${item}`).join('\n')}

### Long-term Strategy
${report.prevention.longTerm.map(item => `- ${item}`).join('\n')}

---

**Detected by:** ${report.detectedBy}
${report.resolvedBy ? `**Resolved by:** ${report.resolvedBy}` : ''}
**Generated by:** PostMortem AI (Bob)
`;
  };

  const copyReport = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownReport());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const downloadReport = () => {
    const markdown = generateMarkdownReport();
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-${report.incidentId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const duration = report.impact.duration;
  const hours = Math.floor(duration / 60);
  const minutes = duration % 60;
  const durationStr = hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="card p-6 space-y-6"
    >
      {/* Header */}
      <div className="flex items-start justify-between pb-4 border-b border-border">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <h3 className="text-lg font-bold text-foreground">Incident Report</h3>
            <span className={`px-2 py-1 rounded text-xs font-bold ${getSeverityColor(report.severity)}`}>
              {report.severity}
            </span>
            <span className={`px-2 py-1 rounded text-xs font-semibold border ${getStatusColor(report.status)}`}>
              {report.status.toUpperCase()}
            </span>
          </div>
          <p className="text-sm text-text-secondary">
            {report.detectedAt.toLocaleString('en-US', {
              month: 'short',
              day: 'numeric',
              year: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
              timeZoneName: 'short'
            })}
          </p>
          <p className="text-xs text-text-muted mt-1">ID: {report.incidentId}</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={copyReport}
            className="btn-secondary px-3 py-2 text-sm flex items-center gap-2"
            title="Copy to clipboard"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy
              </>
            )}
          </button>
          <button
            onClick={downloadReport}
            className="btn-primary px-3 py-2 text-sm flex items-center gap-2"
            title="Download report"
          >
            <Download className="w-4 h-4" />
            Download
          </button>
        </div>
      </div>

      {/* Title */}
      <div>
        <h4 className="text-xl font-bold text-foreground">{report.title}</h4>
      </div>

      {/* Impact Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="p-4 bg-surface rounded-xl border border-border">
          <div className="flex items-center gap-2 mb-2">
            <Clock className="w-4 h-4 text-text-muted" />
            <p className="text-xs font-semibold text-text-muted">DURATION</p>
          </div>
          <p className="text-2xl font-bold text-foreground">{durationStr}</p>
        </div>
        <div className="p-4 bg-surface rounded-xl border border-border">
          <div className="flex items-center gap-2 mb-2">
            <Users className="w-4 h-4 text-text-muted" />
            <p className="text-xs font-semibold text-text-muted">USERS HIT</p>
          </div>
          <p className="text-2xl font-bold text-foreground">
            {report.impact.usersAffected >= 1000
              ? `${(report.impact.usersAffected / 1000).toFixed(1)}k`
              : report.impact.usersAffected}
          </p>
        </div>
        {report.impact.revenueImpact && (
          <div className="p-4 bg-surface rounded-xl border border-border">
            <div className="flex items-center gap-2 mb-2">
              <DollarSign className="w-4 h-4 text-text-muted" />
              <p className="text-xs font-semibold text-text-muted">EST. IMPACT</p>
            </div>
            <p className="text-2xl font-bold text-error">
              ${report.impact.revenueImpact >= 1000
                ? `${(report.impact.revenueImpact / 1000).toFixed(0)}k`
                : report.impact.revenueImpact}
            </p>
          </div>
        )}
        <div className="p-4 bg-surface rounded-xl border border-border">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle className="w-4 h-4 text-text-muted" />
            <p className="text-xs font-semibold text-text-muted">SERVICES</p>
          </div>
          <p className="text-2xl font-bold text-foreground">{report.impact.servicesAffected.length}</p>
        </div>
      </div>

      {/* Timeline */}
      <div className="space-y-3">
        <h4 className="text-sm font-semibold text-foreground">TIMELINE</h4>
        <div className="space-y-3">
          {report.timeline.map((event, index) => (
            <div key={index} className="flex gap-4">
              <div className="flex flex-col items-center">
                <div className={`w-3 h-3 rounded-full ${index === report.timeline.length - 1 ? 'bg-success' : 'bg-primary'}`}></div>
                {index < report.timeline.length - 1 && (
                  <div className="w-0.5 h-full bg-border mt-1"></div>
                )}
              </div>
              <div className="flex-1 pb-4">
                <p className="text-sm font-semibold text-foreground mb-1">
                  {event.timestamp.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })} — {event.event}
                </p>
                {event.actor && (
                  <p className="text-xs text-text-muted">{event.actor}</p>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Root Cause */}
      <div className="space-y-3">
        <h4 className="text-sm font-semibold text-foreground">ROOT CAUSE</h4>
        <div className="p-4 bg-warning/5 border border-warning/20 rounded-xl">
          <p className="text-sm text-foreground leading-relaxed">{report.rootCause}</p>
        </div>
      </div>

      {/* Fix Applied */}
      <div className="space-y-3">
        <h4 className="text-sm font-semibold text-foreground">FIX APPLIED</h4>
        <div className="p-4 bg-success/5 border border-success/20 rounded-xl">
          <p className="text-sm text-foreground leading-relaxed">{report.fixApplied}</p>
        </div>
      </div>

      {/* Prevention */}
      <div className="space-y-4">
        <h4 className="text-sm font-semibold text-foreground">PREVENTION</h4>

        {/* Immediate */}
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-error" />
            <p className="text-xs font-semibold text-error">Immediate Actions</p>
          </div>
          <ul className="space-y-2 ml-6">
            {report.prevention.immediate.map((item, index) => (
              <li key={index} className="flex items-start gap-2 text-sm text-text-secondary">
                <span className="w-1.5 h-1.5 rounded-full bg-error mt-1.5 flex-shrink-0"></span>
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* Short-term */}
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-warning" />
            <p className="text-xs font-semibold text-warning">Short-term Improvements</p>
          </div>
          <ul className="space-y-2 ml-6">
            {report.prevention.shortTerm.map((item, index) => (
              <li key={index} className="flex items-start gap-2 text-sm text-text-secondary">
                <span className="w-1.5 h-1.5 rounded-full bg-warning mt-1.5 flex-shrink-0"></span>
                {item}
              </li>
            ))}
          </ul>
        </div>

        {/* Long-term */}
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Shield className="w-4 h-4 text-success" />
            <p className="text-xs font-semibold text-success">Long-term Strategy</p>
          </div>
          <ul className="space-y-2 ml-6">
            {report.prevention.longTerm.map((item, index) => (
              <li key={index} className="flex items-start gap-2 text-sm text-text-secondary">
                <span className="w-1.5 h-1.5 rounded-full bg-success mt-1.5 flex-shrink-0"></span>
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Footer */}
      <div className="pt-4 border-t border-border text-xs text-text-muted space-y-1">
        <p><span className="font-semibold">Detected by:</span> {report.detectedBy}</p>
        {report.resolvedBy && (
          <p><span className="font-semibold">Resolved by:</span> {report.resolvedBy}</p>
        )}
        <p><span className="font-semibold">Generated by:</span> PostMortem AI (Bob)</p>
      </div>
    </motion.div>
  );
}

// Made with Bob